baseURL = "https://ckross01.com"
languageCode = "en-us"
title = "Ckross01 Blog"
theme = "https://github.com/vaga/hugo-theme-m10c.git"

[params]
  author = "Chris Ross"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula turpis sit amet elit pretium."
  [[params.social]]
    name = "github"
    url = "https://github.com/ckross01"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/ckross01"
